export const LOADING_START = 'HOME/LOADING_START'
export const LOADED_IMG = 'HOME/LOADED_IMG'
export const REQUEST_IMG = 'HOME/REQUEST_IMG'

export const ADD_IMG_CARD_TO_HISTORY = 'HISTORY/ADD_IMG_CARD_TO_HISTORY'
export const CHANGE_PAGE = 'HISTORY/CHANGE_PAGE'
